apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-bff
  namespace: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: myapp-bff
    repoURL: https://github.com/Hemankita/template-argocd-test.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
